sudo: required # 관리자 권한갖기

language: generic # 언어(플랫폼)을 선택, python, node 등

services: 
  - docker

before_install:  # 스크립트 실행 전, 환경 설정 해야함.
# 출력문 
  - echo "start Creating and image with dockerfile"
# build 이미지 생성
  - docker build -t alstjrchl97/docker-react-app -f Dockerfile.dev ./ # 도커파일을 이용해 이미지를 생성해줘야됌

script: # 빌드 후 테스트
  - docker run -e CI=true alstjrchl97/docker-react-app npm run test -- --coverage
  # 이미지를 이용하여, 컨테이너 생성 후 "npm run test" -- --coverage의 경우, 상세한 내역이 출력시킴

# Bucket Name : elasticbeanstalk-us-west-2-345145132436
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-053195428231"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
