version: "3"
services: 
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: app_frontend  
    volumes:
      # 노드모듈 참조x
      - /app/node_modules
      # 프론트앱 전부 참조 
      - ./frontend:/app
    stdin_open: true
    # react 중요부분.

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: alstjrchl97
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306

  nginx:
    # 재시작 정책 
    # - no: 재시작 절대 x
    # always : 항상 재시작
    # on-failure : 에러코드와 함께 컨테이너 정지 시, 재시작
    # unless-stopped : 개발자가 임의로 멈추려고 할때 빼고, 항상 재시작함.
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
    container_name: app_nginx_proxy

  # 개발환경 시에는 
  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports: 
  #     - "3306:3306"
  #   volumes: 
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/

  #   environment: 
  #     MYSQL_ROOT_PASSWORD: minseok
  #     MYSQL_DATABASE: myapp